# Generated by Django 5.1.6 on 2025-02-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='descricao',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
