# Generated by Django 5.1.6 on 2025-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_aluno_email_aluno_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('estudantes', models.ManyToManyField(to='alunos.aluno')),
            ],
        ),
    ]
